services:
  ssl-wearables:
    build: .
    container_name: ssl-wearables-container
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    command: tail -f /dev/null
